// app/lib/locations.ts

export type City = {
  slug: string;
  name: string;
  country: "NZ" | "AU";
};

function nz(slug: string, name: string): City {
  return { slug, name, country: "NZ" };
}
function au(slug: string, name: string): City {
  return { slug, name, country: "AU" };
}

/**
 * NUCLEAR LOCATION SET
 * - Keep slugs lowercase with hyphens
 * - Expand anytime by adding entries below
 */
export const LOCATIONS: City[] = [
  // -------------------- 🇳🇿 NEW ZEALAND --------------------
  nz("auckland", "Auckland"),
  nz("wellington", "Wellington"),
  nz("christchurch", "Christchurch"),
  nz("hamilton", "Hamilton"),
  nz("tauranga", "Tauranga"),
  nz("dunedin", "Dunedin"),
  nz("palmerston-north", "Palmerston North"),
  nz("napier", "Napier"),
  nz("hastings", "Hastings"),
  nz("nelson", "Nelson"),
  nz("rotorua", "Rotorua"),
  nz("new-plymouth", "New Plymouth"),
  nz("whangarei", "Whangārei"),
  nz("invercargill", "Invercargill"),
  nz("whanganui", "Whanganui"),
  nz("giscorne", "Gisborne"),
  nz("taupo", "Taupō"),
  nz("timaru", "Timaru"),
  nz("blenheim", "Blenheim"),
  nz("queenstown", "Queenstown"),
  nz("wanaka", "Wānaka"),
  nz("pukekohe", "Pukekohe"),
  nz("manukau", "Manukau"),
  nz("north-shore", "North Shore"),
  nz("west-auckland", "West Auckland"),
  nz("east-auckland", "East Auckland"),
  nz("south-auckland", "South Auckland"),
  nz("mount-maunganui", "Mount Maunganui"),
  nz("papamoa", "Papamoa"),
  nz("cambridge", "Cambridge"),
  nz("te-awamutu", "Te Awamutu"),
  nz("matamata", "Matamata"),
  nz("thames", "Thames"),
  nz("pokeno", "Pōkeno"),
  nz("kawerau", "Kawerau"),
  nz("whakatane", "Whakatāne"),
  nz("katikati", "Katikati"),
  nz("waihi", "Waihi"),
  nz("feilding", "Feilding"),
  nz("levin", "Levin"),
  nz("kapiti", "Kāpiti Coast"),
  nz("porirua", "Porirua"),
  nz("lower-hutt", "Lower Hutt"),
  nz("upper-hutt", "Upper Hutt"),
  nz("masterton", "Masterton"),
  nz("paraparaumu", "Paraparaumu"),
  nz("ashburton", "Ashburton"),
  nz("rangiora", "Rangiora"),
  nz("rolleston", "Rolleston"),
  nz("kaiapoi", "Kaiapoi"),
  nz("greymouth", "Greymouth"),
  nz("hokitika", "Hokitika"),
  nz("kaikoura", "Kaikōura"),
  nz("oamaru", "Oamaru"),
  nz("gore", "Gore"),

  // -------------------- 🇦🇺 AUSTRALIA --------------------
  au("sydney", "Sydney"),
  au("melbourne", "Melbourne"),
  au("brisbane", "Brisbane"),
  au("perth", "Perth"),
  au("adelaide", "Adelaide"),
  au("canberra", "Canberra"),
  au("gold-coast", "Gold Coast"),
  au("sunshine-coast", "Sunshine Coast"),
  au("newcastle", "Newcastle"),
  au("wollongong", "Wollongong"),
  au("geelong", "Geelong"),
  au("townsville", "Townsville"),
  au("cairns", "Cairns"),
  au("toowoomba", "Toowoomba"),
  au("ballarat", "Ballarat"),
  au("bendigo", "Bendigo"),
  au("albury", "Albury"),
  au("wagga-wagga", "Wagga Wagga"),
  au("hobart", "Hobart"),
  au("launceston", "Launceston"),
  au("darwin", "Darwin"),
  au("alice-springs", "Alice Springs"),
  au("bunbury", "Bunbury"),
  au("mandurah", "Mandurah"),
  au("rockingham", "Rockingham"),
  au("joondalup", "Joondalup"),
  au("fremantle", "Fremantle"),
  au("geraldton", "Geraldton"),
  au("kalgoorlie", "Kalgoorlie"),
  au("broome", "Broome"),
  au("karratha", "Karratha"),
  au("port-hedland", "Port Hedland"),
  au("mackay", "Mackay"),
  au("bundaberg", "Bundaberg"),
  au("hervey-bay", "Hervey Bay"),
  au("gladstone", "Gladstone"),
  au("rockhampton", "Rockhampton"),
  au("gympie", "Gympie"),
  au("noosa", "Noosa"),
  au("byron-bay", "Byron Bay"),
  au("lismore", "Lismore"),
  au("tamworth", "Tamworth"),
  au("armidale", "Armidale"),
  au("coffs-harbour", "Coffs Harbour"),
  au("port-macquarie", "Port Macquarie"),
  au("central-coast", "Central Coast"),
  au("blue-mountains", "Blue Mountains"),
  au("penrith", "Penrith"),
  au("parramatta", "Parramatta"),
  au("liverpool", "Liverpool"),
  au("campbelltown", "Campbelltown"),
  au("dandenong", "Dandenong"),
  au("frankston", "Frankston"),
  au("ringwood", "Ringwood"),
  au("werribee", "Werribee"),
  au("shepparton", "Shepparton"),
  au("mildura", "Mildura"),
  au("traralgon", "Traralgon"),
  au("sale", "Sale"),
  au("morwell", "Morwell"),
  au("mount-gambier", "Mount Gambier"),
  au("whyalla", "Whyalla"),
  au("port-lincoln", "Port Lincoln"),
  au("gawler", "Gawler"),
  au("noarlunga", "Noarlunga"),
  au("logan", "Logan"),
  au("ipswich", "Ipswich"),
  au("redland-bay", "Redland Bay"),
  au("caboolture", "Caboolture"),
  au("north-lakes", "North Lakes"),
  au("surfers-paradise", "Surfers Paradise"),
  au("broadbeach", "Broadbeach"),
  au("southport", "Southport"),
  au("palm-beach", "Palm Beach"),
  au("airlie-beach", "Airlie Beach"),
  au("kiama", "Kiama"),
  au("batemans-bay", "Batemans Bay"),
  au("orange", "Orange"),
  au("dubbo", "Dubbo"),
  au("bathurst", "Bathurst"),
  au("broken-hill", "Broken Hill"),
  au("margaret-river", "Margaret River"),
];
