export async function createRun(
  userId: string,
  projectId: string,
  input: { prompt?: string; status?: string } = {}
): Promise<Run> {
  const runId = `run_${cryptoRandomId()}`;

  const run: Run = {
    id: runId,
    projectId,
    status: "queued",
    prompt: input.prompt,
    createdAt: kvNowISO(),
    files: [],
  };

  await kvJsonSet(runKey(userId, runId), run);
  await kv.sadd(runsIndexKey(userId, projectId), runId);

  // ---- Demo lifecycle ----
  setTimeout(async () => {
    await kvJsonSet(runKey(userId, runId), { ...run, status: "running" });

    setTimeout(async () => {
      await kvJsonSet(runKey(userId, runId), {
        ...run,
        status: "complete",
        files: [
          {
            path: "app/page.tsx",
            content: `
export default function Home() {
  return (
    <main style={{ padding: 40, fontFamily: "system-ui" }}>
      <h1>Generated Landing Page</h1>
      <p>This page was generated by the AI Website Builder.</p>
    </main>
  );
}
`.trim(),
          },
        ],
      });
    }, 1500);
  }, 500);

  return run;
}
