import { NextResponse } from "next/server";
import { kv } from "@vercel/kv";

export async function POST(
  req: Request,
  { params }: { params: { projectId: string; runId: string } }
) {
  try {
    const { projectId, runId } = params;

    // Get run (optional, but safe)
    const run = await kv.get(`run:${runId}`);

    // Generate deterministic HTML (simple but real)
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Generated Site</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
      background: #0f172a;
      color: #e5e7eb;
      margin: 0;
      padding: 0;
    }
    header {
      padding: 80px 20px;
      text-align: center;
      background: linear-gradient(135deg, #020617, #020617);
    }
    h1 {
      font-size: 48px;
      margin-bottom: 12px;
    }
    p {
      font-size: 18px;
      opacity: 0.9;
    }
    section {
      max-width: 1000px;
      margin: 0 auto;
      padding: 60px 20px;
    }
    .card {
      background: #020617;
      border: 1px solid #1e293b;
      border-radius: 16px;
      padding: 24px;
      margin-bottom: 24px;
    }
  </style>
</head>
<body>
  <header>
    <h1>AI Generated Website</h1>
    <p>Project: ${projectId}</p>
    <p>Run: ${runId}</p>
  </header>

  <section>
    <div class="card">
      <h2>About</h2>
      <p>This website was generated by your AI Website Builder.</p>
    </div>

    <div class="card">
      <h2>Services</h2>
      <p>Automated websites, fast builds, zero setup.</p>
    </div>

    <div class="card">
      <h2>Contact</h2>
      <p>Email: hello@example.com</p>
    </div>
  </section>
</body>
</html>
`;

    // ✅ SAVE LATEST (existing behaviour)
    await kv.set("generated:latest", {
      html,
      projectId,
      runId,
      createdAt: new Date().toISOString(),
    });

    // ✅ SAVE PER-RUN (THIS IS THE FIX)
    await kv.set(`generated:run:${runId}`, {
      html,
      projectId,
      runId,
      createdAt: new Date().toISOString(),
    });

    // Mark run completed (optional but good)
    if (run && typeof run === "object") {
      await kv.set(`run:${runId}`, {
        ...(run as any),
        status: "completed",
        completedAt: new Date().toISOString(),
      });
    }

    return NextResponse.json({
      ok: true,
      runId,
      projectId,
      saved: ["generated:latest", `generated:run:${runId}`],
    });
  } catch (e: any) {
    return NextResponse.json(
      { ok: false, error: e?.message || "Execution failed" },
      { status: 500 }
    );
  }
}
