import { NextResponse } from "next/server";
import { kv } from "@vercel/kv";

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function safeString(v: unknown): string {
  return typeof v === "string" ? v.trim() : "";
}

function generateHtml(opts: { projectId: string; runId: string; prompt: string }) {
  const { projectId, runId, prompt } = opts;
  const p = prompt.toLowerCase();

  const title =
    p.includes("business") ? "Business Website" :
    p.includes("portfolio") ? "Portfolio" :
    p.includes("landing") ? "Landing Page" :
    "Generated Website";

  const subtitle =
    p.includes("business") ? "A clean modern business site." :
    p.includes("portfolio") ? "A creator portfolio with projects." :
    p.includes("landing") ? "A high-converting landing page." :
    "A clean, modern website generated by your builder.";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root { color-scheme: dark; }
    body {
      font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
      margin: 0; padding: 0;
      background: #0b1220; color: #e5e7eb;
    }
    header {
      padding: 72px 20px;
      text-align: center;
      background: radial-gradient(1200px 600px at 50% 0%, #111c34, #0b1220);
      border-bottom: 1px solid #1f2a44;
    }
    h1 { font-size: 46px; margin: 0 0 10px; }
    p { margin: 0; opacity: 0.9; }
    .wrap { max-width: 980px; margin: 0 auto; padding: 42px 20px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 16px; }
    .card {
      background: #0f172a;
      border: 1px solid #233055;
      border-radius: 16px;
      padding: 18px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.25);
    }
    .card h2 { margin: 0 0 8px; font-size: 18px; }
    .muted { opacity: 0.8; font-size: 13px; }
    code { background: #0b1220; border: 1px solid #233055; padding: 2px 6px; border-radius: 8px; }
    footer { padding: 24px 20px; text-align:center; border-top: 1px solid #1f2a44; opacity: 0.85; }
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
    <p>${subtitle}</p>
    <p class="muted" style="margin-top:14px;">
      Project: <code>${projectId}</code> • Run: <code>${runId}</code>
    </p>
  </header>

  <div class="wrap">
    <div class="grid">
      <div class="card">
        <h2>About</h2>
        <p class="muted">Generated from your prompt:</p>
        <p style="margin-top:10px;">${escapeHtml(prompt)}</p>
      </div>

      <div class="card">
        <h2>Sections</h2>
        <p>Hero • Features • Testimonials • Contact</p>
        <p class="muted" style="margin-top:10px;">(Deterministic demo HTML)</p>
      </div>

      <div class="card">
        <h2>Next</h2>
        <p>Export • Publish • Domain connect</p>
        <p class="muted" style="margin-top:10px;">Your builder can grow from here.</p>
      </div>
    </div>
  </div>

  <footer>
    Generated by <strong>my-saas-app</strong>
  </footer>
</body>
</html>`;
}

export async function POST(
  req: Request,
  { params }: { params: { projectId: string; runId: string } }
) {
  try {
    const { projectId, runId } = params;

    // ✅ Always end up with a STRING prompt (never {})
    const runAny = await kv.get(`run:${runId}`);
    let runPrompt = "";

    if (runAny && typeof runAny === "object") {
      runPrompt = safeString((runAny as any).prompt);
    }

    if (!runPrompt) {
      const body = await req.json().catch(() => ({} as any));
      runPrompt = safeString(body?.prompt);
    }

    if (!runPrompt) {
      runPrompt = "Build a modern website. Clean minimal styling.";
    }

    const html = generateHtml({ projectId, runId, prompt: runPrompt });

    const payload = {
      html,
      projectId,
      runId,
      createdAt: new Date().toISOString(),
    };

    // ✅ Save latest
    await kv.set("generated:latest", payload);

    // ✅ Save per-run
    await kv.set(`generated:run:${runId}`, payload);

    // Update run status (optional, but good)
    if (runAny && typeof runAny === "object") {
      await kv.set(`run:${runId}`, {
        ...(runAny as any),
        status: "completed",
        completedAt: new Date().toISOString(),
      });
    }

    return NextResponse.json({
      ok: true,
      projectId,
      runId,
      saved: ["generated:latest", `generated:run:${runId}`],
    });
  } catch (e: any) {
    return NextResponse.json(
      { ok: false, error: e?.message || "Execution failed" },
      { status: 500 }
    );
  }
}
