// src/app/lib/publishedContentStore.ts
import { kv } from "./kv";

export type PublishedSection = {
  id: string;        // stable id like "hero", "cta", "features"
  heading: string;
  body: string;
};

export type PublishedPage = {
  slug: "" | "about" | "pricing" | "faq" | "contact";
  title: string;
  description?: string;
  sections: PublishedSection[];
};

export type PublishedSiteContent = {
  projectId: string;
  updatedAt: string; // ISO string
  pages: Record<string, PublishedPage>; // keys: "", "about", "pricing", "faq", "contact"
};

function key(projectId: string) {
  return `pub:content:${projectId}`;
}

export function defaultPublishedContent(projectId: string): PublishedSiteContent {
  const now = new Date().toISOString();

  const mk = (
    slug: "" | "about" | "pricing" | "faq" | "contact",
    title: string,
    description: string,
    sections: PublishedSection[]
  ): PublishedPage => ({
    slug,
    title,
    description,
    sections,
  });

  return {
    projectId,
    updatedAt: now,
    pages: {
      "": mk("", "Home", "Welcome to our website", [
        {
          id: "hero",
          heading: "Welcome",
          body:
            "This site was generated by the Agent (KV content store). You can regenerate content anytime from the Agents page.",
        },
        {
          id: "features",
          heading: "What you get",
          body:
            "Fast pages, clean structure, and a foundation ready for real templates, SEO, and conversion improvements.",
        },
        {
          id: "cta",
          heading: "Get started",
          body:
            "If you’re ready, go to Pricing to choose a plan or Contact to reach us.",
        },
      ]),
      about: mk("about", "About", "About this website", [
        {
          id: "mission",
          heading: "Our mission",
          body:
            "We help people launch professional websites quickly with automation-first workflows.",
        },
        {
          id: "story",
          heading: "Our story",
          body:
            "This content is stored in KV so updates can happen instantly without redeploying code.",
        },
      ]),
      pricing: mk("pricing", "Pricing", "Plans and pricing", [
        {
          id: "plans",
          heading: "Simple plans",
          body:
            "Starter: Great for testing. Pro: Ideal for publishing and growing. Enterprise: For advanced needs.",
        },
        {
          id: "value",
          heading: "Value focus",
          body:
            "Pay for outcomes: fast setup, clean pages, and the ability to evolve content instantly.",
        },
      ]),
      faq: mk("faq", "FAQ", "Frequently asked questions", [
        {
          id: "q1",
          heading: "Can I update content without redeploying?",
          body:
            "Yes. The agent writes content to KV, and the published renderer reads it live.",
        },
        {
          id: "q2",
          heading: "Is this SEO-ready?",
          body:
            "Yes — you already have metadata, canonical handling, sitemap, and robots. Now content is dynamic too.",
        },
      ]),
      contact: mk("contact", "Contact", "How to contact us", [
        {
          id: "contact",
          heading: "Contact",
          body:
            "Add your preferred contact method here (email, form, helpdesk). This is KV content and can be regenerated anytime.",
        },
      ]),
    },
  };
}

export async function getPublishedContent(projectId: string): Promise<PublishedSiteContent | null> {
  const raw = await kv.get(key(projectId));
  if (!raw) return null;

  try {
    return JSON.parse(raw) as PublishedSiteContent;
  } catch {
    return null;
  }
}

export async function setPublishedContent(content: PublishedSiteContent): Promise<void> {
  await kv.set(key(content.projectId), JSON.stringify(content));
}

export async function ensurePublishedContent(projectId: string): Promise<PublishedSiteContent> {
  const existing = await getPublishedContent(projectId);
  if (existing) return existing;

  const created = defaultPublishedContent(projectId);
  await setPublishedContent(created);
  return created;
}
